### ISSUE TITLE
Issue - Error when building image Dockerfile

### ISSUE THREAD

**Issue by ansred** [AykutSarac/jsoncrack.com#307]
**Issue:**
Issue - Error when building image Dockerfile           


**OS:**
MacOS ARM

**Error:**
```
[+] Building 237.8s (13/15)                                                                                                                                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 168B                                                                                                                                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/nginxinc/nginx-unprivileged:latest                                                                                                                                                                                                     1.7s
 => [internal] load metadata for docker.io/library/node:14-buster                                                                                                                                                                                                                 1.8s
 => [auth] nginxinc/nginx-unprivileged:pull token for registry-1.docker.io                                                                                                                                                                                                        0.0s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                                                                                       0.0s
 => [builder 1/5] FROM docker.io/library/node:14-buster@sha256:0c888dc647d36f5a895edb6b1b1c96ae81064455e0cdeee0792e14927604ca99                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 1.43MB                                                                                                                                                                                                                                               0.0s
 => CACHED [stage-1 1/3] FROM docker.io/nginxinc/nginx-unprivileged@sha256:2874ba155bf0852427ea0254edeba824186911ff0299df61ff88527d29594983                                                                                                                                       0.0s
 => CACHED [builder 2/5] WORKDIR /src                                                                                                                                                                                                                                             0.0s
 => [builder 3/5] COPY . /src                                                                                                                                                                                                                                                     0.1s
 => [builder 4/5] RUN yarn install --legacy-peer-deps                                                                                                                                                                                                                           173.8s
 => ERROR [builder 5/5] RUN yarn run build                                                                                                                                                                                                                                       62.0s
------                                                                                                                                                                                                                                                                                 
 > [builder 5/5] RUN yarn run build:                                                                                                                                                                                                                                                   
#12 1.781 yarn run v1.22.19                                                                                                                                                                                                                                                            
#12 2.007 $ next build && next export                                                                                                                                                                                                                                                  
#12 4.111 info  - Loaded env from /src/.env.production                                                                                                                                                                                                                                 
#12 8.074 Attention: Next.js now collects completely anonymous telemetry regarding usage.                                                                                                                                                                                              
#12 8.074 This information is used to shape Next.js' roadmap and prioritize features.
#12 8.074 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#12 8.074 https://nextjs.org/telemetry
#12 8.074 
#12 8.618 info  - Linting and checking validity of types...
#12 17.41 error - ESLint: Failed to load plugin 'testing-library' declared in '.eslintrc.json#overrides[0]': Cannot find module 'eslint-plugin-testing-library' Require stack: - /src/__placeholder__.js Referenced from: /src/.eslintrc.json
#12 56.44 info  - Creating an optimized production build...
#12 59.02 > [PWA] Compile client (static)
#12 59.02 > [PWA] Auto register service worker with: /src/node_modules/next-pwa/register.js
#12 59.02 > [PWA] Service worker: /src/public/sw.js
#12 59.02 > [PWA]   url: /sw.js
#12 59.02 > [PWA]   scope: /editor/
#12 59.51 > [PWA] Compile server
#12 60.50 > [PWA] Compile server
#12 61.36 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#12 61.58 Segmentation fault
#12 61.67 error Command failed with exit code 139.
#12 61.67 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn run build]: exit code: 139
```

_Originally posted by @ansred in https://github.com/AykutSarac/jsoncrack.com/issues/289#issuecomment-1409110360_
            



**Note:**
Everything works fine with older versions 2.0.0 + 2.1.0 and I can build the docker image just fine, issue starts with 2.5 and above

Here is example of a working docker build
```
red@mach jsoncrack.com-2.1.0 % docker build -t ansred/jsoncrack-1-amd64 . --no-cache=true --platform=linux/amd64
[+] Building 506.9s (16/16) FINISHED                                                                                                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 496B                                                                                                                                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/nginxinc/nginx-unprivileged:latest                                                                                                                                                                                                     1.8s
 => [internal] load metadata for docker.io/library/node:14-buster                                                                                                                                                                                                                 1.7s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                                                                                       0.0s
 => [auth] nginxinc/nginx-unprivileged:pull token for registry-1.docker.io                                                                                                                                                                                                        0.0s
 => [builder 1/5] FROM docker.io/library/node:14-buster@sha256:0c888dc647d36f5a895edb6b1b1c96ae81064455e0cdeee0792e14927604ca99                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 1.26MB                                                                                                                                                                                                                                               0.0s
 => CACHED [stage-1 1/3] FROM docker.io/nginxinc/nginx-unprivileged@sha256:2874ba155bf0852427ea0254edeba824186911ff0299df61ff88527d29594983                                                                                                                                       0.0s
 => CACHED [builder 2/5] WORKDIR /src                                                                                                                                                                                                                                             0.0s
 => [builder 3/5] COPY . /src                                                                                                                                                                                                                                                     0.1s
 => [builder 4/5] RUN yarn install --legacy-peer-deps                                                                                                                                                                                                                           145.4s
 => [builder 5/5] RUN yarn run build                                                                                                                                                                                                                                            358.6s 
 => [stage-1 2/3] COPY --from=builder /src/out /app                                                                                                                                                                                                                               0.0s 
 => [stage-1 3/3] COPY default.conf /etc/nginx/conf.d/default.conf                                                                                                                                                                                                                0.0s 
 => exporting to image                                                                                                                                                                                                                                                            0.0s 
 => => exporting layers                                                                                                                                                                                                                                                           0.0s 
 => => writing image sha256:1b7f2a0a3b23eaf99ac005c9764d3da23fe1b6688197e421567c710fc7700110                                                                                                                                                                                      0.0s 
 => => naming to docker.io/ansred/jsoncrack-1-amd64   

```

**Comment by ansred** [comment]
Not sure what happened, but I tried all the releases from the latest back to 2.0.0 and all worked fine now.

```
jsoncrack.com-2.6.0 % docker build -t ansred/jsoncrack-1-amd64 . --no-cache=true --platform=linux/amd64
[+] Building 554.1s (16/16) FINISHED                                                                                                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 496B                                                                                                                                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/nginxinc/nginx-unprivileged:latest                                                                                                                                                                                                     1.7s
 => [internal] load metadata for docker.io/library/node:14-buster                                                                                                                                                                                                                 1.6s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                                                                                       0.0s
 => [auth] nginxinc/nginx-unprivileged:pull token for registry-1.docker.io                                                                                                                                                                                                        0.0s
 => CACHED [stage-1 1/3] FROM docker.io/nginxinc/nginx-unprivileged@sha256:2874ba155bf0852427ea0254edeba824186911ff0299df61ff88527d29594983                                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                                                                                                 0.1s
 => => transferring context: 1.43MB                                                                                                                                                                                                                                               0.0s
 => [builder 1/5] FROM docker.io/library/node:14-buster@sha256:0c888dc647d36f5a895edb6b1b1c96ae81064455e0cdeee0792e14927604ca99                                                                                                                                                   0.0s
 => CACHED [builder 2/5] WORKDIR /src                                                                                                                                                                                                                                             0.0s
 => [builder 3/5] COPY . /src                                                                                                                                                                                                                                                     0.0s
 => [builder 4/5] RUN yarn install --legacy-peer-deps                                                                                                                                                                                                                           165.6s
 => [builder 5/5] RUN yarn run build                                                                                                                                                                                                                                            385.5s 
 => [stage-1 2/3] COPY --from=builder /src/out /app                                                                                                                                                                                                                               0.0s 
 => [stage-1 3/3] COPY default.conf /etc/nginx/conf.d/default.conf                                                                                                                                                                                                                0.0s 
 => exporting to image                                                                                                                                                                                                                                                            0.0s 
 => => exporting layers                                                                                                                                                                                                                                                           0.0s 
 => => writing image sha256:4d59ade887ebc357fc620c17c7b1fe48b7b74e2df70dc0ca52a96202230a26e2                                                                                                                                                                                      0.0s 
 => => naming to docker.io/ansred/jsoncrack-1-amd64             
```

Closing.
